### ISSUE TITLE
Script 2 : data cleaning/pre-processing, transforming

### ISSUE THREAD

**Issue by eboylestanley** [UBC-MDS/CPD#21]

**Comment by elabandari** [comment]
Hi @ebs33,

I just wrapped up the adding the demographics data into the EDA.ipynb file as well as calculating the complaint rate variable. There is a PR up with these changes.

As I was going through the process,  a couple of suggestions came to mind that may help in the data cleaning and later stages:
1. Removing the UID column and joining solely on link_UID since link_UID is consistent across all 4 dataframes while there is some variation in the UID column across dataframes.
2. Subsetting the data into a dataframe that contains only the variables we plan to use in our analysis.

**Comment by eboylestanley** [comment]
Thank @elabandari!  I have employed your suggestions, I linked only on `link_IUD` and also removed unnecessary columns.

**Comment by eboylestanley** [comment]
- Create two dataframes as output files.  complaints_all_staff and complaints_police
