### ISSUE TITLE
Milestone 2 General Feedback

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/CPD#56]
Hi CPD Group!

I really enjoyed exploring your project!

I have some comments for your Report:

1)title grammar in Readme for second sentence should change - maybe something like ' Investigation of the relationship between salary and number of complaints received'
2) A more descriptive title to your report would be good, then next heading can be removed and just move to the Summary, put authors at the top under the title, and add date last edited
3) graph labels very small
4) I appreciate the thorough explanation and walk through of the data with both figures and text, however, I am wondering if most of this can be kept in your EDA document, and the overall findings summarized in text.
Example: Maybe remove Figure 1 and 2, and just explain the trends, because they make me ask a lot of questions and you then answer them nicely in FIgure 3, but in the report only FIgure 3 is important for me to understand I think.
5) Figure 9 values are confusing to read. $ sign is not needed in front of the numbers on the x-axis, and is in the axis label. Maybe 50, 75, 100 with Salary in $1000 as the axis label would be easier to read

**Comment by micahkwok** [comment]
@elabandari @ebs33 

4) I've removed figures 1 & 2 as per her example, but I think she wants us to really cut down on the plots for our report document. Do you guys have a preference of which ones to keep? I was thinking of removing 4,6 and 7 as they're nice to see and understand but it's not the 'key plots' and can be pretty easily described textually.

**Comment by elabandari** [comment]
Hi Analise, 

Thank you for all these suggestions. We agree with all of them and decided to implement them all.

1)title grammar in Readme for second sentence should change - maybe something like ' Investigation of the relationship between salary and number of complaints received'
- Addressed 

2) A more descriptive title to your report would be good, then next heading can be removed and just move to the Summary, put authors at the top under the title, and add date last edited
- Addressed 

3) graph labels very small
-Addressed 

4) I appreciate the thorough explanation and walk through of the data with both figures and text, however, I am wondering if most of this can be kept in your EDA document, and the overall findings summarized in text.
Example: Maybe remove Figure 1 and 2, and just explain the trends, because they make me ask a lot of questions and you then answer them nicely in FIgure 3, but in the report only FIgure 3 is important for me to understand I think.
-Addressed 

5) Figure 9 values are confusing to read. $ sign is not needed in front of the numbers on the x-axis, and is in the axis label. Maybe 50, 75, 100 with Salary in $1000 as the axis label would be easier to read
-Addressed
