### ISSUE TITLE
Peer Review Feedback

### ISSUE THREAD

**Issue by ssyayayy** [UBC-MDS/CPD#59]
Thanks for the great report! This is a very interesting topic and I enjoy reading it!

I just have a few things you may consider to add or amend.

- Regarding the inferential question, it would be helpful to clarify a bit more when you say comparing **A** policy staff's salary with the number of complaints **THEY** receive per year in the `Introduction` and `Results and Discussion` sections. It can be a typo, but just thought it needs to be pointed out because it is one of the most important thing in this report. 

- Figure titles for 6 and 7 are aligned differently from the other figures. 

- It would be good to show more details about the variables used for regression. For example, how did you generate the complaints per year if it is not directly provided by the source data? Any missing values exist? How did you deal with them? Are you comparing the salary of a policy staff and the total number of complaints he received for the **same corresponding year**? I assume the two are more comparable if they are from the same year. If I misunderstood anything, please feel free to let me know.

Good luck!

Ivy

**Comment by elabandari** [comment]
Hi Ivy, 

Thanks for taking the time to give us feedback, we really appreciate it! 

Below is your feedback addressed 

Regarding the inferential question, it would be helpful to clarify a bit more when you say comparing A policy staff's salary with the number of complaints THEY receive per year in the Introduction and Results and Discussion sections. It can be a typo, but just thought it needs to be pointed out because it is one of the most important thing in this report.
- We have changed the wording to make this more clear! 

Figure titles for 6 and 7 are aligned differently from the other figures.
- We realigned the figures and moved them to our EDA section.

It would be good to show more details about the variables used for regression. For example, how did you generate the complaints per year if it is not directly provided by the source data? Any missing values exist? How did you deal with them? Are you comparing the salary of a policy staff and the total number of complaints he received for the same corresponding year? I assume the two are more comparable if they are from the same year. If I misunderstood anything, please feel free to let me know.
- We added a data processing section to our methods to outline how we calculated complaint_per_year and dealt with missing values. 

Thanks!
