### ISSUE TITLE
Peer review feedback

### ISSUE THREAD

**Issue by charlessuresh** [UBC-MDS/CPD#68]
Hey Group 15,

I'm assigned to do a peer review for your group project (Release 0.2.0) this week. Overall, great work on this project!

My review/feedback:

- Documentation: The project is properly documented and very clear to understand.

- Code: The code in all the scripts are readable, well organized and reproducible.

- Analysis and Reasoning: The analysis and reasoning is pretty clear and accurate.

- Communication: The report is very well written. It is clear and easy to follow

I have a few suggestions listed below (already reviewed other peer feedbacks to avoid overlapping issues):

- Since, as per the report, you would be examining the coefficients of regression and their p-values to determine if the associations are significant, it maybe makes sense to specify the significance level (alpha)

- Since the focus is on linear regression, it maybe makes sense to have a section in the beginning dedicated to specifying the assumptions made for the regression analysis and if any of these assumptions are being violated

- There is a bit of over plotting in 'Figure 8. Correlation Matrix'. Maybe you could adjust the `alpha` and the `size` parameters?

- Instead of restricting to Linear Regression, you could also explore other regression models such as Polynomial Regression, Spline Models, Generalized additive models, etc

- In the MLR with `salary_scaled` and `gender` explanatory variables, there is an extra slope coefficient for non-existent variable `comment_percentage` that's been added in error

**Comment by elabandari** [comment]
Hi Charles, 

Thanks for your feedback! It's helpful as we wrap up our project. Below are your comments addressed 

Since, as per the report, you would be examining the coefficients of regression and their p-values to determine if the associations are significant, it maybe makes sense to specify the significance level (alpha)

- alpha has been added 

Since the focus is on linear regression, it maybe makes sense to have a section in the beginning dedicated to specifying the assumptions made for the regression analysis and if any of these assumptions are being violated
- We have outlined where the assumptions are violated in our limitations section now 😄 

There is a bit of over plotting in 'Figure 8. Correlation Matrix'. Maybe you could adjust the alpha and the size parameters?
- Great suggestion but we will not be able to implement this change due to time constraints.

Instead of restricting to Linear Regression, you could also explore other regression models such as Polynomial Regression, Spline Models, Generalized additive models, etc
- Great suggestion but this is beyond the scope of the project at this stage. 

In the MLR with salary_scaled and gender explanatory variables, there is an extra slope coefficient for non-existent variable comment_percentage that's been added in error
- Yes! That was a typo. Good eye.
