### ISSUE TITLE
Initial Rough EDA Update

### ISSUE THREAD

**Issue by micahkwok** [UBC-MDS/CPD#8]
I played around with the data, but since it's such messy unorganized work I wasn't sure if I should push it or even where to push it. But it might be helpful for Elanor if you're working on it tomorrow morning. This is not really an issue so feel free to close it as needed. 

Downloading Files Script/Steps
```# author: Micah Kwok
# date: 2020-11-19

#script documenting steps for downloading data files

# Salary file
python download_data.py --url=https://github.com/invinst/chicago-police-data/blob/master/data/unified_data/salary/salary-ranks_2002-2017_2017-09.csv.gz?raw=true --path=salary_ranks

# Complaints accused file
python download_data.py --url=https://github.com/invinst/chicago-police-data/blob/master/data/unified_data/complaints/complaints-accused.csv.gz?raw=true --path=complaints_accused

# Complaints file
python download_data.py --url=https://github.com/invinst/chicago-police-data/blob/master/data/unified_data/complaints/complaints-complaints.csv.gz?raw=true --path=complaints
```

Merging Data in R, Playing Around with EDA (not in script format, I played with this in .Rmd)
```
library(tidyverse)

salary_df <- read.csv('src/salary_ranks')
complaints_accused_df <- read.csv('src/complaints_accused')
complaints_df <- read.csv('src/complaints')

#joined on UID although, to note there is a link_UID column
df_merged <- left_join(salary_df,complaints_accused_df, by = 'UID')
df_merged <- left_join(df_merged,complaints_df, by = 'cr_id')

#boxplot
ggplot(df_merged) + 
  aes(x = salary,
      y = cleaned_rank) +
  geom_boxplot() + 
  scale_x_continuous(labels = scales::label_dollar())

GGally::ggcorr(df_merged)
```

**Comment by elabandari** [comment]
Hi Micah, 

Thanks for all hard your work on this. 

Elanor, I combined Micah's work and my work and sent a PR with this EDA. You can find the EDA.ipynb file in the /src directory and the dowloaded .csv files in the /data directory as part of this PR. Please note that the EDA.ipynb will not live in the /src directory in the long-term but I did not have a better place for it at the moment.

I would like to note that Micah and I took a slightly different approach to the joins so it would be good to determine what the best order is for the joins at this step.
 
The data dictionary ([link here](https://github.com/invinst/chicago-police-data/blob/master/data/unified_data/data-dictionary/data-dictionary.yaml)) is really helpful for interpreting the variables. I think either of the link_UID or the UID is fine for our purposes. I think link_UID is probably a better option since its compatible with all versions of their identification system based on my understanding of the description in the data dictionary.

Great work so far team 💪

**Comment by elabandari** [comment]
One more note: I (and I assume Micah also based on the code above) decided to use the salary ranks data file because the full salary dataset had too many irrelevant columns at this point 😅

**Comment by eboylestanley** [comment]
I have added some "data cleaning" steps to the EDA.  
- I changed the initial data import to default to a character data type for all columns, then modified necessary columns to dbl or data later in the analysis.  I did think because the default format was changing the `cr_id` into a dbl,  and converting any `cr_id` values  that started with a "CR" suffix to NAs. 
- There were a lot of duplicate values in the complaints and accused datasets.   I have add some code to remove the duplicates I have identified, it is somewhat arbitrary which duplicates got dropped, but I tried to be consistent between the two datasets.  
- I filtered the data for the years 20025-2015.  
- I updated the joins to remove unnecessary duplicate columns and match the salary to incident years.

**Comment by elabandari** [comment]
Thanks for the thorough data cleaning Elanor. 

The assignment [instructions](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md#4-exploratory-data-analysis-in-a-literate-code-document) mention that the EDA.ipynb file should be placed in either the src or an eda subdirectory so I am moving that over to a new eda subdirectory.
